// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'call_recording.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1129777401934766731),
    name: 'CallRecording',
    lastPropertyId: const obx_int.IdUid(14, 1640598700276949746),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7394413666724893418),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1998871522104139264),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1585788067327812316),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 796738717241149260),
        name: 'dateReceived',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9028374141982975860),
        name: 'size',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1643088239178992730),
        name: 'callLogName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5075515361319572843),
        name: 'callLogNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5676656790061249769),
        name: 'callLogTimestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5694066843006161463),
        name: 'callLogDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8018864138188008400),
        name: 'callLogType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5629527891168702420),
        name: 'contactDisplayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1844246036353323711),
        name: 'contactPhoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3206435324609867733),
        name: 'transcription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1640598700276949746),
        name: 'isTranscribed',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 1129777401934766731),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CallRecording: obx_int.EntityDefinition<CallRecording>(
      model: _entities[0],
      toOneRelations: (CallRecording object) => [],
      toManyRelations: (CallRecording object) => {},
      getId: (CallRecording object) => object.id,
      setId: (CallRecording object, int id) {
        object.id = id;
      },
      objectToFB: (CallRecording object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final fileNameOffset = fbb.writeString(object.fileName);
        final callLogNameOffset = object.callLogName == null
            ? null
            : fbb.writeString(object.callLogName!);
        final callLogNumberOffset = object.callLogNumber == null
            ? null
            : fbb.writeString(object.callLogNumber!);
        final callLogTypeOffset = object.callLogType == null
            ? null
            : fbb.writeString(object.callLogType!);
        final contactDisplayNameOffset = object.contactDisplayName == null
            ? null
            : fbb.writeString(object.contactDisplayName!);
        final contactPhoneNumberOffset = object.contactPhoneNumber == null
            ? null
            : fbb.writeString(object.contactPhoneNumber!);
        final transcriptionOffset = object.transcription == null
            ? null
            : fbb.writeString(object.transcription!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, filePathOffset);
        fbb.addOffset(2, fileNameOffset);
        fbb.addInt64(3, object.dateReceived.millisecondsSinceEpoch);
        fbb.addInt64(4, object.size);
        fbb.addOffset(5, callLogNameOffset);
        fbb.addOffset(6, callLogNumberOffset);
        fbb.addInt64(7, object.callLogTimestamp);
        fbb.addInt64(8, object.callLogDuration);
        fbb.addOffset(9, callLogTypeOffset);
        fbb.addOffset(10, contactDisplayNameOffset);
        fbb.addOffset(11, contactPhoneNumberOffset);
        fbb.addOffset(12, transcriptionOffset);
        fbb.addBool(13, object.isTranscribed);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateReceivedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final sizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final transcriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final isTranscribedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final callLogNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final callLogNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final callLogTimestampParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final callLogDurationParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final callLogTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final contactDisplayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final contactPhoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object = CallRecording(
          id: idParam,
          filePath: filePathParam,
          fileName: fileNameParam,
          dateReceived: dateReceivedParam,
          size: sizeParam,
          transcription: transcriptionParam,
          isTranscribed: isTranscribedParam,
          callLogName: callLogNameParam,
          callLogNumber: callLogNumberParam,
          callLogTimestamp: callLogTimestampParam,
          callLogDuration: callLogDurationParam,
          callLogType: callLogTypeParam,
          contactDisplayName: contactDisplayNameParam,
          contactPhoneNumber: contactPhoneNumberParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CallRecording] entity fields to define ObjectBox queries.
class CallRecording_ {
  /// See [CallRecording.id].
  static final id = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[0],
  );

  /// See [CallRecording.filePath].
  static final filePath = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[1],
  );

  /// See [CallRecording.fileName].
  static final fileName = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[2],
  );

  /// See [CallRecording.dateReceived].
  static final dateReceived = obx.QueryDateProperty<CallRecording>(
    _entities[0].properties[3],
  );

  /// See [CallRecording.size].
  static final size = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[4],
  );

  /// See [CallRecording.callLogName].
  static final callLogName = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[5],
  );

  /// See [CallRecording.callLogNumber].
  static final callLogNumber = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[6],
  );

  /// See [CallRecording.callLogTimestamp].
  static final callLogTimestamp = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[7],
  );

  /// See [CallRecording.callLogDuration].
  static final callLogDuration = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[8],
  );

  /// See [CallRecording.callLogType].
  static final callLogType = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[9],
  );

  /// See [CallRecording.contactDisplayName].
  static final contactDisplayName = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[10],
  );

  /// See [CallRecording.contactPhoneNumber].
  static final contactPhoneNumber = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[11],
  );

  /// See [CallRecording.transcription].
  static final transcription = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[12],
  );

  /// See [CallRecording.isTranscribed].
  static final isTranscribed = obx.QueryBooleanProperty<CallRecording>(
    _entities[0].properties[13],
  );
}
