// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'call_recording.dart';
import 'transcription.dart';
import 'vector.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1129777401934766731),
    name: 'CallRecording',
    lastPropertyId: const obx_int.IdUid(19, 5033993400993430075),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7394413666724893418),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1998871522104139264),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1585788067327812316),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 796738717241149260),
        name: 'dateReceived',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9028374141982975860),
        name: 'size',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1643088239178992730),
        name: 'callLogName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5075515361319572843),
        name: 'callLogNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5676656790061249769),
        name: 'callLogTimestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5694066843006161463),
        name: 'callLogDuration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8018864138188008400),
        name: 'callLogType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5629527891168702420),
        name: 'contactDisplayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1844246036353323711),
        name: 'contactPhoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3206872270662915398),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5019509352335271350),
        name: 'isSummarized',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4467617504955635511),
        name: 'isVectorized',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 1542662358134272479),
        name: 'transcriptionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3553733258145972750),
        relationField: 'transcription',
        relationTarget: 'Transcription',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 1145702904327087714),
        name: 'vectors',
        targetId: const obx_int.IdUid(4, 7207501107027180539),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5997333617814549602),
    name: 'Transcription',
    lastPropertyId: const obx_int.IdUid(2, 3624769585747519849),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7238597987244518746),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3624769585747519849),
        name: 'fullText',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 3839041035632917224),
        name: 'segments',
        targetId: const obx_int.IdUid(3, 5540166720134433378),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5540166720134433378),
    name: 'TranscriptionSegment',
    lastPropertyId: const obx_int.IdUid(4, 7961878321535195645),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6169050643238046542),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8691558193173316776),
        name: 'start',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3391235606172649556),
        name: 'end',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7961878321535195645),
        name: 'text',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7207501107027180539),
    name: 'Vector',
    lastPropertyId: const obx_int.IdUid(2, 3659062560848625605),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1471828595172578770),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3659062560848625605),
        name: 'embedding',
        type: 29,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 7207501107027180539),
    lastIndexId: const obx_int.IdUid(2, 7961270678120073529),
    lastRelationId: const obx_int.IdUid(2, 1145702904327087714),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [7961270678120073529],
    retiredPropertyUids: const [
      3206435324609867733,
      1640598700276949746,
      5033993400993430075,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CallRecording: obx_int.EntityDefinition<CallRecording>(
      model: _entities[0],
      toOneRelations: (CallRecording object) => [object.transcription],
      toManyRelations: (CallRecording object) => {
        obx_int.RelInfo<CallRecording>.toMany(2, object.id): object.vectors,
      },
      getId: (CallRecording object) => object.id,
      setId: (CallRecording object, int id) {
        object.id = id;
      },
      objectToFB: (CallRecording object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final fileNameOffset = fbb.writeString(object.fileName);
        final callLogNameOffset = object.callLogName == null
            ? null
            : fbb.writeString(object.callLogName!);
        final callLogNumberOffset = object.callLogNumber == null
            ? null
            : fbb.writeString(object.callLogNumber!);
        final callLogTypeOffset = object.callLogType == null
            ? null
            : fbb.writeString(object.callLogType!);
        final contactDisplayNameOffset = object.contactDisplayName == null
            ? null
            : fbb.writeString(object.contactDisplayName!);
        final contactPhoneNumberOffset = object.contactPhoneNumber == null
            ? null
            : fbb.writeString(object.contactPhoneNumber!);
        final summaryOffset = object.summary == null
            ? null
            : fbb.writeString(object.summary!);
        fbb.startTable(20);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, filePathOffset);
        fbb.addOffset(2, fileNameOffset);
        fbb.addInt64(3, object.dateReceived.millisecondsSinceEpoch);
        fbb.addInt64(4, object.size);
        fbb.addOffset(5, callLogNameOffset);
        fbb.addOffset(6, callLogNumberOffset);
        fbb.addInt64(7, object.callLogTimestamp);
        fbb.addInt64(8, object.callLogDuration);
        fbb.addOffset(9, callLogTypeOffset);
        fbb.addOffset(10, contactDisplayNameOffset);
        fbb.addOffset(11, contactPhoneNumberOffset);
        fbb.addOffset(14, summaryOffset);
        fbb.addBool(15, object.isSummarized);
        fbb.addBool(16, object.isVectorized);
        fbb.addInt64(17, object.transcription.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateReceivedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final sizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final isSummarizedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          34,
          false,
        );
        final isVectorizedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          36,
          false,
        );
        final callLogNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final callLogNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final callLogTimestampParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final callLogDurationParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final callLogTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final contactDisplayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final contactPhoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object = CallRecording(
          id: idParam,
          filePath: filePathParam,
          fileName: fileNameParam,
          dateReceived: dateReceivedParam,
          size: sizeParam,
          summary: summaryParam,
          isSummarized: isSummarizedParam,
          isVectorized: isVectorizedParam,
          callLogName: callLogNameParam,
          callLogNumber: callLogNumberParam,
          callLogTimestamp: callLogTimestampParam,
          callLogDuration: callLogDurationParam,
          callLogType: callLogTypeParam,
          contactDisplayName: contactDisplayNameParam,
          contactPhoneNumber: contactPhoneNumberParam,
        );
        object.transcription.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        object.transcription.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<CallRecording>(
          object.vectors,
          store,
          obx_int.RelInfo<CallRecording>.toMany(2, object.id),
        );
        return object;
      },
    ),
    Transcription: obx_int.EntityDefinition<Transcription>(
      model: _entities[1],
      toOneRelations: (Transcription object) => [],
      toManyRelations: (Transcription object) => {
        obx_int.RelInfo<Transcription>.toMany(1, object.id): object.segments,
      },
      getId: (Transcription object) => object.id,
      setId: (Transcription object, int id) {
        object.id = id;
      },
      objectToFB: (Transcription object, fb.Builder fbb) {
        final fullTextOffset = fbb.writeString(object.fullText);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, fullTextOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fullTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Transcription(id: idParam, fullText: fullTextParam);
        obx_int.InternalToManyAccess.setRelInfo<Transcription>(
          object.segments,
          store,
          obx_int.RelInfo<Transcription>.toMany(1, object.id),
        );
        return object;
      },
    ),
    TranscriptionSegment: obx_int.EntityDefinition<TranscriptionSegment>(
      model: _entities[2],
      toOneRelations: (TranscriptionSegment object) => [],
      toManyRelations: (TranscriptionSegment object) => {},
      getId: (TranscriptionSegment object) => object.id,
      setId: (TranscriptionSegment object, int id) {
        object.id = id;
      },
      objectToFB: (TranscriptionSegment object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.start);
        fbb.addInt64(2, object.end);
        fbb.addOffset(3, textOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final startParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final endParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = TranscriptionSegment(
          id: idParam,
          start: startParam,
          end: endParam,
          text: textParam,
        );

        return object;
      },
    ),
    Vector: obx_int.EntityDefinition<Vector>(
      model: _entities[3],
      toOneRelations: (Vector object) => [],
      toManyRelations: (Vector object) => {},
      getId: (Vector object) => object.id,
      setId: (Vector object, int id) {
        object.id = id;
      },
      objectToFB: (Vector object, fb.Builder fbb) {
        final embeddingOffset = fbb.writeListFloat64(object.embedding);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final embeddingParam = const fb.ListReader<double>(
          fb.Float64Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 6, []);
        final object = Vector(id: idParam, embedding: embeddingParam);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CallRecording] entity fields to define ObjectBox queries.
class CallRecording_ {
  /// See [CallRecording.id].
  static final id = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[0],
  );

  /// See [CallRecording.filePath].
  static final filePath = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[1],
  );

  /// See [CallRecording.fileName].
  static final fileName = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[2],
  );

  /// See [CallRecording.dateReceived].
  static final dateReceived = obx.QueryDateProperty<CallRecording>(
    _entities[0].properties[3],
  );

  /// See [CallRecording.size].
  static final size = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[4],
  );

  /// See [CallRecording.callLogName].
  static final callLogName = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[5],
  );

  /// See [CallRecording.callLogNumber].
  static final callLogNumber = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[6],
  );

  /// See [CallRecording.callLogTimestamp].
  static final callLogTimestamp = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[7],
  );

  /// See [CallRecording.callLogDuration].
  static final callLogDuration = obx.QueryIntegerProperty<CallRecording>(
    _entities[0].properties[8],
  );

  /// See [CallRecording.callLogType].
  static final callLogType = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[9],
  );

  /// See [CallRecording.contactDisplayName].
  static final contactDisplayName = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[10],
  );

  /// See [CallRecording.contactPhoneNumber].
  static final contactPhoneNumber = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[11],
  );

  /// See [CallRecording.summary].
  static final summary = obx.QueryStringProperty<CallRecording>(
    _entities[0].properties[12],
  );

  /// See [CallRecording.isSummarized].
  static final isSummarized = obx.QueryBooleanProperty<CallRecording>(
    _entities[0].properties[13],
  );

  /// See [CallRecording.isVectorized].
  static final isVectorized = obx.QueryBooleanProperty<CallRecording>(
    _entities[0].properties[14],
  );

  /// See [CallRecording.transcription].
  static final transcription =
      obx.QueryRelationToOne<CallRecording, Transcription>(
        _entities[0].properties[15],
      );

  /// see [CallRecording.vectors]
  static final vectors = obx.QueryRelationToMany<CallRecording, Vector>(
    _entities[0].relations[0],
  );
}

/// [Transcription] entity fields to define ObjectBox queries.
class Transcription_ {
  /// See [Transcription.id].
  static final id = obx.QueryIntegerProperty<Transcription>(
    _entities[1].properties[0],
  );

  /// See [Transcription.fullText].
  static final fullText = obx.QueryStringProperty<Transcription>(
    _entities[1].properties[1],
  );

  /// see [Transcription.segments]
  static final segments =
      obx.QueryRelationToMany<Transcription, TranscriptionSegment>(
        _entities[1].relations[0],
      );
}

/// [TranscriptionSegment] entity fields to define ObjectBox queries.
class TranscriptionSegment_ {
  /// See [TranscriptionSegment.id].
  static final id = obx.QueryIntegerProperty<TranscriptionSegment>(
    _entities[2].properties[0],
  );

  /// See [TranscriptionSegment.start].
  static final start = obx.QueryIntegerProperty<TranscriptionSegment>(
    _entities[2].properties[1],
  );

  /// See [TranscriptionSegment.end].
  static final end = obx.QueryIntegerProperty<TranscriptionSegment>(
    _entities[2].properties[2],
  );

  /// See [TranscriptionSegment.text].
  static final text = obx.QueryStringProperty<TranscriptionSegment>(
    _entities[2].properties[3],
  );
}

/// [Vector] entity fields to define ObjectBox queries.
class Vector_ {
  /// See [Vector.id].
  static final id = obx.QueryIntegerProperty<Vector>(
    _entities[3].properties[0],
  );

  /// See [Vector.embedding].
  static final embedding = obx.QueryDoubleVectorProperty<Vector>(
    _entities[3].properties[1],
  );
}
